apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-rolling
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: webapp-rolling
  template:
    metadata:
      labels:
        app: webapp-rolling
    spec:
      containers:
        - name: webapp
          image: tutulchakma/node-jwt-mongo-api:V1
          ports:
            - containerPort: 3000

