apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  selector:
    app: webapp
    version: blue  # Initially point to blue
  ports:
    - port: 80
      targetPort: 3000
  type: NodePort
